version: '3'
services:
  ui:
    build:
      context: ./ui
    ports:
      - "8085:8080"  # Map the UI container's port 80 to host port 8080
    depends_on:
      - api  # Ensure the API service is started before the UI
  api:
    build:
      context: ./api
    ports:
      - "9095:9095"  # Map the API container's port 5000 to host port 5000
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'SPACED_REP'
      MYSQL_ROOT_PASSWORD: 'root'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "23306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  